FROM ubuntu:latest

MAINTAINER Shashi Kumar "imshashikumar01@gmail.com"

RUN apt-get update && apt-get install -y openjdk-8-jdk

CMD ["/bin/bash"]

#CMD = docker image build -t imshashikumar01/jdk-image-ubuntu:0.0.1 .
